projects:
  notesapp:
    schemaPath: ../amplifyapp /graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /Users/michaelfedulov/Files_Local/Test/amplifyapp /graphql
